server:
  port: 8088
spring:
  application:
    name: spring-batch-study
  #mysql 相关
  datasource:
    url: jdbc:mysql://47.105.78.73:3306/kevin?characterEncoding=utf8&useSSL=false
    username: root
    password: 111111
    #创建spring batch 需要的表，利用已经写好的schema文件
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
#    driver-class-name: com.mysql.jdbc.Driver //已经是的deprecated
    driver-class-name: com.mysql.cj.jdbc.Driver


  batch:
    #初始化的时候会执行上面的schema-mysql.sql中的表
    initialize-schema: always




